slots = ["None",
         "Head",
         "Neck",
         "Shoulder",
         "Shirt",
         "Chest",
         "Waist",
         "Legs",
         "Feet",
         "Wrist",
         "Hands",
         "Finger",
         "Trinket",
         "One-Hand",
         "Shield",
         "Ranged",
         "Cloak",
         "Two-Hand",
         "Bag",
         "Tabard",
         "Chest",
         "Main Hand",
         "Off Hand",
         "Held In Off-hand",
         "Ammo",
         "Thrown",
         "Ranged",
         "Relic"]
good_inventory_slots = [1,2,3,5,6,7,8,9,10,11,12,15,16,20,26]

stats_used = {3:'agility',
              32:'crit',
              36:'haste',
              49:'mastery',
              59:'multistrike',
              40:'versatility',
              73:'agility', # really agility/int stat
             }